export const environment = {
    production: false,
    domain: 'http://localhost:8080',
    saveSocial: '/save/social?resumeId=',
    saveSkill: '/save/skill?resumeId=',
    saveResume: '/save/resume',
    saveEducation: '/save/education?resumeId=',
    saveExperience: '/save/experience?resumeId=',
    saveResponsibility: '/save/responsibility?resumeId=',
    deleteSocial: '/delete/social?socialId=',
    deleteSkill: '/delete/skill?skillId=',
    deleteResume: '/delete/resume?resumeId=',
    deleteEducation: '/delete/education?educationId=',
    deleteExperience: '/delete/experience?experienceId=',
    deleteResponsibility: '/delete/responsibility?',
    register: '/auth/register',
    getUserList: '/get/userList',
    getResumeById: '/get/resume/byId?resumeId=',
    getUserDto: '/get/userDto',
};
